# Generated by Django 5.0 on 2023-12-22 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images')),
                ('password', models.CharField()),
                ('birth_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('is_hidden_bd', models.BooleanField()),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='sent', max_length=10)),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='main_app.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(through='main_app.UserFriend', to='main_app.user'),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('archived_at', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='main_app.user')),
                ('users', models.ManyToManyField(to='main_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('link_url', models.URLField()),
                ('description', models.CharField(max_length=150)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.user')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wishlist')),
            ],
        ),
    ]
