# Generated by Django 5.0 on 2024-01-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='description',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
