# Generated by Django 5.0 on 2024-05-13 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_wishlist_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='is_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userfriendrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rejected_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
