# Generated by Django 5.0 on 2024-05-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_gift_is_priority_userfriendrequest_rejected_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gift',
            options={'verbose_name': 'Подарок', 'verbose_name_plural': 'Подарки'},
        ),
    ]
