# Generated by Django 5.0 on 2024-06-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_gift_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfriend',
            options={'verbose_name': 'Друзья', 'verbose_name_plural': 'Друг'},
        ),
        migrations.AlterModelOptions(
            name='userfriendrequest',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Вишлист', 'verbose_name_plural': 'Вишлисты'},
        ),
        migrations.AlterField(
            model_name='gift',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='gift',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
