# Generated by Django 5.0 on 2024-06-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_userfriend_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfriend',
            options={'verbose_name': 'Друг', 'verbose_name_plural': 'Друзья'},
        ),
    ]
